### ISSUE TITLE
OSError: -202 at startup

### ISSUE THREAD

**Issue by wieluk** [yunnanpl/esp32_python_eq3#16]
Hey there thanks for your work but I can't get it working on my esp32. 

At startup this happens:

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4540
ho 0 tail 12 room 4
load:0x40078000,len:12344
ho 0 tail 12 room 4
load:0x40080400,len:4124
entry 0x40080680
- ip 192.168.0.63
- time 719523391
- mqtt ping 98
= booted
- load wl failed, setting default, this is ok  [Errno 2] ENOENT
= f mqtt recover
Traceback (most recent call last):
  File "main.py", line 1310, in <module>
  File "main.py", line 1291, in fmqtt_recover
  File "simple2.py", line 53, in connect
OSError: -202
MicroPython v1.18 on 2022-01-17; ESP32 module with ESP32
Type "help()" for more information.
>>>
```

Do you have any idea what went wrong?

**Comment by wieluk** [comment]
Hey I noticed the mistake. It was in the mqtt serverhost. I write "192.168.0.37:1883" the port was the problem. How am I supposed to write the host?

**Comment by wieluk** [comment]
The problem was that I added the port to the mqtt server
